version: '3.8'

services:
  app:
    container_name: backend-app
    build:
      context: .
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
    command: npm start

  db:
    image: postgres:14-alpine
    container_name: my-postgres-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prisma_node
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
