apiVersion: apps/v1
kind: Deployment
metadata:
  name: prisma-node-api
  labels:
    app: prisma-node-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prisma-node-api
  template:
    metadata:
      labels:
        app: prisma-node-api
    spec:
      containers:
        - name: prisma-node-api
          image: ${DOCKER_REGISTRY}/prisma-node-api:${IMAGE_TAG}
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: 'production'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prisma-node-secrets
                  key: database-url
          resources:
            requests:
              cpu: '100m'
              memory: '256Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: prisma-node-api
spec:
  selector:
    app: prisma-node-api
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
